# Copyright 2025-2026 Inria

# Defaults taken from jrl-cmakemodules doxygen.cmake.
# PROJECT_NAME, PROJECT_NUMBER and PROJECT_BRIEF are already set by
# FindDoxygen from PROJECT_NAME, PROJECT_VERSION and PROJECT_DESCRIPTION.
set(DOXYGEN_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
set(DOXYGEN_STRIP_FROM_PATH ${PROJECT_SOURCE_DIR})
set(DOXYGEN_STRIP_FROM_INC_PATH ${PROJECT_SOURCE_DIR}/include)
set(DOXYGEN_EXTRACT_ALL YES)
set(DOXYGEN_QUIET YES)
set(DOXYGEN_WARN_LOGFILE ${CMAKE_CURRENT_BINARY_DIR}/doxygen.log)
set(DOXYGEN_RECURSIVE YES)
set(
  DOXYGEN_FILE_PATTERNS
  *.cc
  *.cpp
  *.h
  *.hh
  *.hpp
  *.hxx
)
set(DOXYGEN_IMAGE_PATH ${CMAKE_CURRENT_SOURCE_DIR})
set(DOXYGEN_EXAMPLE_PATH ${PROJECT_SOURCE_DIR}/tests)
set(DOXYGEN_USE_MDFILE_AS_MAINPAGE ${PROJECT_SOURCE_DIR}/README.md)
set(DOXYGEN_HTML_OUTPUT doxygen-html)
set(DOXYGEN_GENERATE_TREEVIEW YES)
set(DOXYGEN_USE_MATHJAX YES)
set(DOXYGEN_GENERATE_LATEX NO)
set(DOXYGEN_LATEX_OUTPUT doxygen-latex)
set(DOXYGEN_EXTRA_PACKAGES amssymb amsmath)
set(DOXYGEN_XML_OUTPUT doxygen-xml)
set(DOXYGEN_GENERATE_TAGFILE ${CMAKE_CURRENT_BINARY_DIR}/doxygen-html/${PROJECT_NAME}.doxytag)

if(DOXYGEN_VERSION VERSION_GREATER_EQUAL 1.9.2)
  set(DOXYGEN_MATHJAX_VERSION MathJax_3)
endif()

doxygen_add_docs(
  nanoeigenpy-doc
  ALL
  ${PROJECT_SOURCE_DIR}/include
  ${PROJECT_SOURCE_DIR}/src
  COMMENT "Generating Doxygen documentation"
)

if(INSTALL_DOCUMENTATION)
  install(
    DIRECTORY ${DOXYGEN_OUTPUT_DIRECTORY}/${DOXYGEN_HTML_OUTPUT}
    DESTINATION ${CMAKE_INSTALL_DATAROOTDIR}/doc/${PROJECT_NAME}
    COMPONENT doc
  )
endif()
